### ISSUE TITLE
Numbers are now strings?

### ISSUE THREAD

**Issue by mwm** [hippasus/ExchangeRates#17]
I'm responsible for a tutorial on using the Haskell json parsing library, and recently got a notice that it wasn't working properly talking to your site (BTW, thank you for providing the service).

Upon investigation, it appears that the two numeric values ("rate" and "v") are now returned in quotes, so the automatically generated parser I was using is getting upset at seeing string values when it expects numeric ones.

Any chance of getting the old behavior back?

**Comment by hippasus** [comment]
sorry, didn't notice that. merged pull request from @Cthulhu days ago. Will fix it.

**Comment by hippasus** [comment]
this should be fixed now.

**Comment by GreatOldOne** [comment]
This is the correct way to do it. We don't want to store them as floating points, but rather a decimal representation. That's why it's sent as a string notation.

Once you parse that JSON object simply convert it to your favorite object type.

Decimal(json["rate"]), float(json["rate"]), atof(json->rate) or whatever your language/code uses.
